### ISSUE TITLE
NullPointerException with Sonarqube 5.2

### ISSUE THREAD

**Issue by Gael63** [hmvictor/radar-netbeans#37] opened 2015-12-01 16:39 UTC
Hello,
My radar-netbeans plugin don't want to update the new result of the analyzes when I update the new version of SonarQube (5.0 to 5.2).
The error is :
java.lang.NullPointerException
	at qubexplorer.server.SonarQube.getIssues(SonarQube.java:129)
	at qubexplorer.server.SonarQube.getIssues(SonarQube.java:107)
	at qubexplorer.server.SonarQube.getSummary(SonarQube.java:277)
	at qubexplorer.ui.SummaryTask.execute(SummaryTask.java:28)
	at qubexplorer.ui.SummaryTask.execute(SummaryTask.java:16)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:62)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[catch] at java.lang.Thread.run(Thread.java:744)

My environnement is : 
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) Client VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Windows 7 version 6.1 running on x86; Cp1252; fr_FR (nb)

Thanks for your help.

Gaël.

**Comment by docbrownAA** [comment] 2015-12-08 14:19
I got the same issue but I use Java 8 and windows 8.1

**Comment by hmvictor** [comment] 2016-01-14 04:11
I merged the fix for this issue but there are others caused by changes in the API of Sonar. I'm still searching for solutions.

**Comment by hmvictor** [comment] 2016-01-14 04:12
Many thanks for your contribution Gael63

**Closed** 2016-05-25 05:07 UTC
